POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Cool Blog",
  "author": "Blog writer",
  "url": "www.blog.com",
  "likes": 33
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Cool Blog 2",
  "author": "Blog writer 2",
  "url": "www.blog2.com",
  "likes": 6
}